//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NhaTroEntities : DbContext
    {
        public NhaTroEntities()
            : base("name=NhaTroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<img> imgs { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<savepost> saveposts { get; set; }
        public virtual DbSet<street> streets { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<ward> wards { get; set; }
    }
}
