//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post()
        {
            this.imgs = new HashSet<img>();
        }
    
        public int ID { get; set; }
        public int IDimg { get; set; }
        public string tenTp { get; set; }
        public string tenQuan { get; set; }
        public string tenDuong { get; set; }
        public string tenPhuong { get; set; }
        public string soNha { get; set; }
        public string DiaChiChinhXac { get; set; }
        public string ThongTinMoTa { get; set; }
        public Nullable<int> DienTich { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string DoiTuongChoThue { get; set; }
        public Nullable<int> Gia { get; set; }
        public int IDusers { get; set; }
        public string image { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public Nullable<bool> display { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<img> imgs { get; set; }
        public virtual user user { get; set; }
    }
}
