//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class street
    {
        public long id { get; set; }
        public string C_name { get; set; }
        public string C_prefix { get; set; }
        public Nullable<long> C_province_id { get; set; }
        public Nullable<long> C_district_id { get; set; }
    }
}
